apiVersion: apps/v1
kind: Deployment
metadata:
  name: thecontactbook-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thecontactbook-web
  template:
    metadata:
      labels:
        app: thecontactbook-web
    spec:
      containers:
        - name: web
          # Automatically pulls your freshly built GitHub Actions image
          image: kundanvrs/thecontactbook-web:581a918e936a784ac35fb8d183da0870c5ba0c5f
          imagePullPolicy: IfNotPresent  # <-- Add/change this line
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:secretpass@db:5432/contact_db
---
apiVersion: v1
kind: Service
metadata:
  name: thecontactbook-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  selector:
    app: thecontactbook-web